accounts/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signup_success/', views.SignUpSuccessView.as_view(), name='signup_success'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

photo/urls.py
from django.urls import path
from  .import views

app_name = 'photo'

urlpatterns = [
    # photoアプリへのアクセスはviewsモジュールのIndexViewを実行
    path('', views.IndexView.as_view(), name='index'),
    # 写真投稿ページへのアクセスはviewsモジュールのCreatePhotoViewを実行
    path('post/', views.CreatePhotoView.as_view(), name='post'),
    # 投稿完了ページへのアクセスはviewsモジュールのPostSuccessViewを実行
    path('post_done/', views.PostSuccessView.as_view(), name='post_done'),
    #カテゴリ一覧ページ
    path('photos/<int:category>', views.CategoryView.as_view(), name='photos_cat'),
    # ユーザーの投稿一覧ページ
    path('user-list/<int:user>', views.UserView.as_view(), name='user_list'),
    # 詳細ページ
    path('photo-detail/<int:pk>', views.DetailView.as_view(), name='photo_detail'),
    # マイページ
    path('mypage/', views.MypageView.as_view(), name='mypage'),
    # 投稿削除ページ
    path('photo/<int:pk>/delete/', views.PhotoDeleteView.as_view(), name='photo_delete'),
    # 投稿編集ページ
    path('photo/<int:pk>/update/', views.PhotoUpdateView.as_view(), name='photo_update'),
]

photoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photo.urls')),
    path('', include('accounts.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="password_reset.html"), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"), name='password_reset_complete'),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT
)

photo/models.py
from django.db import models
from accounts.models import CustomUser
from django.contrib.auth.models import User

class Category(models.Model):
    title = models.CharField(verbose_name='カテゴリ', max_length=20)
    
    def __str__(self):
        return self.title
    
class PhotoPost(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, verbose_name='カテゴリ', on_delete=models.PROTECT)
    title = models.CharField(verbose_name='タイトル', max_length=200)
    comment = models.TextField(verbose_name='コメント')
    image1 = models.ImageField(verbose_name='イメージ1', upload_to="photos")
    image2 = models.ImageField(verbose_name='イメージ2', upload_to="photos", blank=True, null=True)
    image3 = models.ImageField(verbose_name='イメージ3', upload_to="photos", blank=True, null=True)
    image4 = models.ImageField(verbose_name='イメージ4', upload_to="photos", blank=True, null=True)
    image5 = models.ImageField(verbose_name='イメージ5', upload_to="photos", blank=True, null=True)
    image6 = models.ImageField(verbose_name='イメージ6', upload_to="photos", blank=True, null=True)
    image7 = models.ImageField(verbose_name='イメージ7', upload_to="photos", blank=True, null=True)
    image8 = models.ImageField(verbose_name='イメージ8', upload_to="photos", blank=True, null=True)
    image9 = models.ImageField(verbose_name='イメージ9', upload_to="photos", blank=True, null=True)
    posted_at = models.DateTimeField(verbose_name='投稿日時', auto_now_add=True)

    def __str__(self):
        return self.title
    

photo/forms.py
from django.forms import ModelForm
from .models import PhotoPost
from django import forms

class PhotoPostForm(ModelForm):
    class Meta:
        model = PhotoPost
        fields = ['category','title','comment','image1', 'image2', 'image3', 'image4', 'image5','image6','image7','image8','image9',]

class SearchForm(forms.Form):
    query = forms.CharField(label='検索するキーワード', max_length=100)

photo/views.py
from django.views.generic import TemplateView, ListView, CreateView, DetailView, DeleteView, UpdateView
from django.urls import reverse_lazy
from .forms import PhotoPostForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .models import PhotoPost
from django.db.models import Q


class IndexView(ListView):
    template_name = 'index.html'
    # 投稿日時の降順に並べる
    queryset = PhotoPost.objects.order_by('-posted_at')
    # 1ページに表示するレコードの件数
    paginate_by = 12

    def get_queryset(self, **kwargs): # 検索機能
        queryset = super().get_queryset(**kwargs)
        query = self.request.GET

        if q := query.get('q'):
            queryset = queryset.filter(
                Q(title__icontains=q) | Q(comment__icontains=q)
            )

        return queryset.order_by('-posted_at')


# デコレーターにより、CreatePhotoViewへのアクセスはログインユーザーに限定される
# ログイン状態でなければsetting.pyのLOGIN_URLにリダイレクトされる
@method_decorator(login_required, name='dispatch')
class CreatePhotoView(CreateView):
    # forms.pyのPhotoPostFormをフォームクラスとして登録
    form_class = PhotoPostForm
    # レンダリングするテンプレート
    template_name = "post_photo.html"
    # フォームデータ登録完了後のリダイレクト先
    success_url = reverse_lazy('photo:post_done')

    def form_valid(self, form):
        # commit=FalseにしてPOSTされたデータを取得
        postdata = form.save(commit=False)
        # 投稿ユーザーのidを取得してモデルのuserフィールドに格納
        postdata.user = self.request.user
        # 投稿データをデータベースに登録
        postdata.save()
        # 戻り値はスーパークラスのform_valid()の戻り値(httpResponseRedirect)
        return super().form_valid(form)
    

class PostSuccessView(TemplateView):
    # index.htmlをレンダリングする
    template_name = 'post_success.html'


class CategoryView(ListView):
    template_name = 'index.html'
    paginate_by = 12

    def get_queryset(self):
        # self.kwargsでキーワードの辞書を取得し、categoryキーの値を取得
        category_id = self.kwargs['category']
        # filterで絞り込み
        categories = PhotoPost.objects.filter(category=category_id).order_by('-posted_at')
        # クエリによって取得されたレコードを返す
        return categories


class UserView(ListView):
    template_name = 'index.html'
    paginate_by = 12
    
    def get_queryset(self):
        # self.kwargsでキーワードの辞書を取得し、userキーの値を取得
        user_id = self.kwargs['user']
        # filterで絞込
        user_list = PhotoPost.objects.filter(user=user_id).order_by('-posted_at')
        # クエリによって取得されたレコードを返す
        return user_list
    

class DetailView(DetailView):
    template_name = 'detail.html'
    model = PhotoPost


class MypageView(ListView):
    template_name = 'mypage.html'
    paginate_by = 12

    def get_queryset(self):
        #現在ログインしているユーザー名はHttpRequest.userに格納されている．filterで絞り込む
        queryset = PhotoPost.objects.filter(user=self.request.user).order_by('-posted_at')
        # クエリによって取得されたレコードを返す
        return queryset
    

class PhotoDeleteView(DeleteView):
    #操作対象はPhotoPostモデル
    model = PhotoPost
    # photo_delete.htmlをレンダリングする
    template_name = 'photo_delete.html'
    # 処理完了後にマイページにリダイレクトする
    success_url = reverse_lazy('photo:mypage')

    def delete(self, request, *args, **kwargs):
        #スーパークラスのdelete()を実行
        return super().delete(request, *args, **kwargs)
    

class PhotoUpdateView(UpdateView):
    model = PhotoPost
    # forms.pyのPhotoPostFormをフォームクラスとして登録
    form_class = PhotoPostForm
    # レンダリングするテンプレート
    template_name = "post_photo.html"
    # フォームデータ登録完了後のリダイレクト先
    success_url = reverse_lazy('photo:post_done')

    def form_valid(self, form):
        # commit=FalseにしてPOSTされたデータを取得
        postdata = form.save(commit=False)
        # 投稿ユーザーのidを取得してモデルのuserフィールドに格納
        postdata.user = self.request.user
        # 投稿データをデータベースに登録
        postdata.save()
        # 戻り値はスーパークラスのform_valid()の戻り値(httpResponseRedirect)
        return super().form_valid(form)

photo/templates/base.html
{% load static %}
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>{% block title %}{% endblock %}</title>    

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/css/splide.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .splide__slide {
        text-align: center;
      }

      .splide__slide img {
        height: 360px;
        width: auto;
      }

    </style>
  </head>

  <body>
    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">Share your football training menu!</h4>
              <p class="text-muted">Let's post and share training menu! You can also refer to the training menu this site!</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Menu</h4>
              <ul class="list-unstyled">

                <!-- navigation menu-->
                {% if user.is_authenticated %}
                <!-- login menu -->
                <li><a href="{% url 'photo:index' %}" class="text-white">Top page</a></li>
                <li><a href="{% url 'photo:mypage' %}" class="text-white">My page</a></li>
                <li><a href="{% url 'accounts:logout' %}" class="text-white">Log out</a></li>
                <li><a href="{% url 'password_reset' %}" class="text-white">Password Reset</a></li>
                <li><a href="mailto:sumiya.soccer.0806@gmail.com" class="text-white">Email me</a></li>
                {% else %}
                <li><a href="{% url 'photo:index' %}" class="text-white">Top page</a></li>
                <li><a href="{% url 'accounts:signup' %}" class="text-white">Sign up</a></li>
                <li><a href="{% url 'accounts:login' %}" class="text-white">Log in</a></li>
                <li><a href="mailto:sumiya.soccer.0806@gmail.com" class="text-white">Email me</a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>

      <!--navigation bar-->
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">

          <a href="{% url 'photo:index' %}" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
            <strong>Training Lab</strong>
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <main>
      <div style="text-align:center;">
        <img class="mb-2" src={% static "img/tohonfc_logo.png" %} alt="" width="100" height="120">
        <h1 class="fw-light"><strong>Training Lab⚽</strong></h1>
        <br>
      </div>
      {% block contents %}{% endblock %}
    </main>

    <footer class="text-muted py-5">
      <div class="container">
        <p class="float-end mb-1">
          <a href="{% url 'photo:index' %}" class="btn btn-secondary my-2">Back to Top</a>
        </p>
        <p class="mb-1"> Trainig Lab is &copy; Bootstrap and created by Shimazaki Sumiya</p>
      </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/js/splide.min.js"></script>
    <script>
      new Splide(".splide").mount();
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>

photo/templates/detail.html
{% extends 'base.html' %}
{% block title %}Photo Detail{% endblock %}

{% block contents %}
    <!--bootstrapのグリッドシステム-->
    <div class="container">

        <!--行を配置-->
        <div class="row">

            <!--写真-->
            <div class="splide" role="group">
                <div class="splide__track">
                    <div class="splide__list">
                        <div class="splide__slide"><img src="{{ object.image1.url }}"></div>
                        {% if object.image2 %}
                        <div class="splide__slide"><img src="{{ object.image2.url }}"></div>
                        {% endif %}
                        {% if object.image3 %}
                        <div class="splide__slide"><img src="{{ object.image3.url }}"></div>
                        {% endif %}
                        {% if object.image4 %}
                        <div class="splide__slide"><img src="{{ object.image4.url }}"></div>
                        {% endif %}
                        {% if object.image5 %}
                        <div class="splide__slide"><img src="{{ object.image5.url }}"></div>
                        {% endif %}
                        {% if object.image6 %}
                        <div class="splide__slide"><img src="{{ object.image6.url }}"></div>
                        {% endif %}
                        {% if object.image7 %}
                        <div class="splide__slide"><img src="{{ object.image7.url }}"></div>
                        {% endif %}
                        {% if object.image8 %}
                        <div class="splide__slide"><img src="{{ object.image8.url }}"></div>
                        {% endif %}
                        {% if object.image9 %}
                        <div class="splide__slide"><img src="{{ object.image9.url }}"></div>
                        {% endif %}
                    </div>
                </div>
            </div>

            <!--列の左右に余白offset-3を入れる-->
            <div class='col offset-1'>
                <br>
                <!--タイトル-->
                <h2>{{ object.title }}</h2>

                <!--コメント-->
                <p>{{ object.comment | linebreaksbr }}</p>
                <br>
                <!--投稿日時-->
                <p>Posted at {{ object.posted_at }}</p>

                <!--ユーザー自身のページの場合、投稿修正&削除できるように設定-->
                {% if request.user == object.user %}
                <form method='POST'>
                    <!--投稿編集ボタン-->
                    <a href="{% url 'photo:photo_update' object.pk %}" class="btn btn-primary my-2">Update</a>
                    <!--投稿削除ボタン-->
                    <a href="{% url 'photo:photo_delete' object.pk %}" class="btn btn-danger my-2">Delete</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

photo/templates/index.html
{% extends 'base.html' %}
{% block title %}Training Lab{% endblock %}

  {% block contents %}

  {% include "photos_search.html" %}

  {% include "photos_list.html" %}

  {% include "pagination.html" %}

{% endblock %}

photo/templates/mypage.html
{% extends 'base.html' %}
{% block title %}Mypage{% endblock %}

{% block contents %}

    {% if user.is_authenticated %}
        <br>
        <div style="text-align:center">
            <h4>{{ user.username }}'s page</h4>
            {% if object_list.count == 0 %}
                <p>{{ user.username }}'s post is nothing.</p>
            {% else %}
                <p><strong>{{ object_list.count }}</strong> post.</p>
            {% endif %}
            <a href="{% url 'photo:post' %}" class="btn btn-primary my-2">Let's post</a>
            <a href="#" class="btn btn-success my-2">My Keep</a>
        </div>
        <hr>
    {% endif %}

    {% include "photos_list.html"  %}
    {% include "pagination.html" %}

{% endblock %}

photo/templates/pagination.html
<ul class="pagination" style="justify-content:center">

    {% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <li class="page-item active">
                <span class="page-link">{{ num }}</span>
            </li>
        {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    {% endif %}
    
</ul>

photo/templates/photo_delete.html
{% extends 'base.html' %}
{% block title %}Photo Detail{% endblock %}

{% block contents %}
    <br>
    <div class="container">
        <div class="row">
            <div class="col offset-3">
                <form method="POST">
                    <br>
                    <p>Is it okay to delete?</p>
                    {% csrf_token %}
                    <button class="btn btn-danger my-2" type="submit">Delete</button>
                    <a href="{% url 'photo:photo_detail' object.pk %}" class="btn btn-secondary my-2">Cancel</a>
            </div>
        </div>
    </div>
{% endblock %}



photo/templates/photos_list.html
<!-- photo list-->
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

      <!-- レコードが格納されたobject_listからレコードを1行ずつrecordに取り出す -->
      {% for record in object_list %}
      <!-- photo aria-->
      <div class="col">
        <div class="card shadow-sm">
          <img src="{{ record.image1.url }}" 
            class="bd-placeholder-img card-img-top"
            type="button"
            onclick="location.href='{% url 'photo:photo_detail' record.pk %}'" 
            width="100%" height="225" 
            xmlns="http://www.w3.org/2000/svg" 
            role="img" aria-label="Placeholder: Thumbnail" 
            preserveAspectRatio="xMidYMid slice"
            focusable="false">
            <title>Placeholder</title>
            <rect width="100%" height="100%" fill="#55595c"/>
          </img>
          <!-- title aria-->
          <div class="card-body">
            <p class="card-text">{{ record.title }}</p>
            <div class="d-flex justify-content-between align-items-center">

              <!-- Category -->
              <a href="{% url 'photo:photos_cat' category=record.category.id %}">
                <small class="text-muted">{{ record.category }}</small>
              </a>
              
              <!-- Username -->
              <a href="{% url 'photo:user_list' user=record.user.id %}">
                <small class="text-muted">{{ record.user.username }}</small>
              </a>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}

    </div>
  </div>
</div>

photo/templates/photos_search.html
<!-- search ＆ sort -->
<section class="py-0 text-center container">
  <div class="row py-lg-2">
    <div class="col-lg-6 col-md-8 mx-auto">

      <!-- search -->
      <form class="d-flex" action="{% url 'photo:index' %}" method="get">
        <input name="q" class="form-control me-2" type="search" placeholder="Search title or contents">
        <button class="btn btn-outline-primary" type="submit">Search</button>
      </form>
      <br>

      <!-- Category sort-->
      <details class="btn btn-light" style="border:1px solid">
        <summary><strong>Category List</strong></summary>
        <button class="btn btn-outline-secondary" onclick="location.href='{% url 'photo:index' %}'">All</button>
        <button class="btn btn-outline-secondary" onclick="location.href='{% url 'photo:photos_cat' category=19 %}'">Practice</button>
        <button class="btn btn-outline-secondary" onclick="location.href='{% url 'photo:photos_cat' category=20 %}'">Game</button>
        <button class="btn btn-outline-secondary" onclick="location.href='{% url 'photo:photos_cat' category=8 %}'">Other</button>
      </details>
    </div>
  </div>
  <br><hr>
</section>

photo/templates/post_photo.html
{% extends 'base.html' %}
{% block title %}Post{% endblock %}

{% block contents %}
<br>
<div class="container">
    <div class="row">
        <div class="col offset-2">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <table>
                    <tr>
                        <th>Category</th>
                        <td>{{ form.category }}</td>
                    </tr>
                    <tr>
                    <th>Title</th>
                    <td>{{ form.title }}</td>
                    </tr>
                    <tr>
                        <th>Comment</th>
                        <td>{{ form.comment }}</td>
                    </tr>
                    
                    <tr>
                        <th>Images</th>
                        <td>{{ form.image1 }}</td>
                    </tr>
                    <tr>
                        <th></th>
                        <td>{{ form.image2 }}</td>
                    </tr>
                    <tr>
                        <th></th>
                        <td>{{ form.image3 }}</td>
                    </tr>
                    <tr>
                        <th></th>
                        <td>{{ form.image4 }}</td>
                    </tr>
                    <tr>
                        <th></th>
                        <td>{{ form.image5 }}</td>
                    </tr>
                    <tr>
                        <th></th>
                        <td>{{ form.image6 }}</td>
                    </tr>
                    <tr>
                        <th></th>
                        <td>{{ form.image7 }}</td>
                    </tr>
                    <tr>
                        <th></th>
                        <td>{{ form.image8 }}</td>
                    </tr>
                    <tr>
                        <th></th>
                        <td>{{ form.image9 }}</td>
                    </tr>
                </table>
                <hr>
                <button class="btn btn-primary my-2" type="submit">Post</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

photo/templates/post_success.html
{% extends 'base.html' %}

{% block title %}Post Success{% endblock %}

{% block contents %}
<br>
<div class="container" style="text-align:center;">
    <div class="row">
        <div class="col offset-0">
            <h4>Post Success!</h4>
            <br><br>
            <button class="btn btn-primary" onclick="location.href='{% url 'photo:mypage' %}'">Continue</button>
        </div>
    </div>
</div>
{% endblock %}